name: Build Neon-OS APK

on:
  push:
    branches: [ principal, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:master

    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        run: |
          # limpa lixo
          rm -rf .buildozer bin
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: neon-bixby-apk
          path: bin/*.apk
          if-no-files-found: error
